"""fixed column name

Revision ID: c7b6ad90d582
Revises: 9d6aea6729aa
Create Date: 2026-04-23 02:23:06.397002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b6ad90d582'
down_revision: Union[str, None] = '9d6aea6729aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('original_url', sa.String(), nullable=False))
    op.drop_column('urls', 'original_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('original_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('urls', 'original_url')
    # ### end Alembic commands ###
